name: test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Action YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install yamllint
        run: sudo apt-get install yamllint

      - name: Lint action.yml
        run: yamllint action.yml
